# Generated by Django 4.1.4 on 2022-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='data_of_death_fbdp',
            field=models.DateField(blank=True, help_text='Дата смерти ФБДП', null=True, verbose_name='Дата смерти ФБДП'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='data_of_death_spu',
            field=models.DateField(blank=True, help_text='Дата смерти СПУ', null=True, verbose_name='Дата смерти СПУ'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_act_number',
            field=models.DateField(blank=True, help_text='Дата актовой записи', null=True, verbose_name='Дата актовой записи'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_include_info_about_death_ils',
            field=models.DateField(blank=True, help_text='Дата включения сведений о смерти в ИЛС', null=True, verbose_name='Дата включения сведений о смерти в ИЛС'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_issue_reference_of_death',
            field=models.DateField(blank=True, help_text='Дата выдачи справки о смерти', null=True, verbose_name='Дата выдачи справки о смерти'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_of_change_personal_data_spu',
            field=models.DateField(blank=True, help_text='Дата изменения анкетных данных в СПУ', null=True, verbose_name='Дата изменения анкетных данных в СПУ'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_of_change_status_ils_spu',
            field=models.DateField(blank=True, help_text='Дата изменения статуса ИЛС СПУ', null=True, verbose_name='Дата изменения статуса ИЛС СПУ'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_start_inshure_pensii',
            field=models.DateField(blank=True, help_text='Дата назначения страховой пенсии', null=True, verbose_name='Дата назначения страховой пенсии'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_transfer_change_in_exd',
            field=models.DateField(blank=True, help_text='Дата передачи изменений в ЕХД', null=True, verbose_name='Дата передачи изменений в ЕХД'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='date_transfer_info_from_nvp_to_fbdp',
            field=models.DateField(blank=True, help_text='Дата передачи сведений из НВП в ФБДП', null=True, verbose_name='Дата передачи сведений из НВП в ФБДП'),
        ),
    ]
