# Generated by Django 4.1.4 on 2022-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_maintable_data_of_death_fbdp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='region_nvp',
            field=models.IntegerField(blank=True, default='', help_text='Район НВП', null=True, verbose_name='Район НВП'),
        ),
    ]
